introduce --parallel to limit concurrent engine calls
docker/compose pull request #10030
Opened 2022-11-30 11:27 UTC by ndeloof

**What I did**
Introduce `--parallel=<int>` for user to limit the concurrency during image pulls
could be later applied to other operations, typically `build` with adequate buildx|kit support for this

**Related issue**

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
![image](https://user-images.githubusercontent.com/132757/204783986-4545e5ee-b7a4-47dc-acd6-76071e2f8b63.png)

2022-11-30 12:15 UTC, glours requested changes
I think tests are failing due to the wrong default value of the `maxConcurrency` attribute.
Docs should also be updated 😉

2022-11-30 12:15 UTC, glours commented on pkg/compose/compose.go
> +	maxConcurrency int
shouldn't it be initialize with a `-1` value by default as the default value for an int will be `0`

2022-12-05 23:55 UTC, laurazard commented
Oh nice! This is something that people have asked for for _a while_, albeit mostly regarding build operations.

2022-12-06 06:23 UTC, ndeloof commented
Build max-parallelism can be controlled, but this takes place on the builder side: https://github.com/docker/buildx/blob/master/docs/guides/resource-limiting.md#max-parallelism

2022-12-06 08:45 UTC, glours approved these changes
LGTM

2022-12-06 08:45 UTC, merged