introduce --timestamp option on compose up
docker/compose pull request #10076
Opened 2022-12-13 18:03 UTC by ndeloof

**What I did**
Add support for `docker compose up --timestamp` to align with same option on `logs` command.

**Related issue**
close https://github.com/docker/compose/issues/5730

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**
![image](https://user-images.githubusercontent.com/132757/207410415-08960d00-3272-4e24-b58d-00b904d75e23.png)

2022-12-13 21:15 UTC, milas requested changes
Logic is good - just the flag name 🙃

2022-12-13 21:15 UTC, milas commented on cmd/compose/up.go
> +	flags.BoolVar(&up.timestamp, "timestamp", false, "Show timestamps.")
For consistency with `compose logs` & `docker logs`, looks like this should be `timestamps` (plural)

https://github.com/docker/cli/blob/990674901b4fdd0bd2d3f91aa84ad3efe225f6fb/cli/command/container/logs.go#L49

https://github.com/docker/compose/blob/0368f190303b28e142f983257171a6f554749313/cmd/compose/logs.go#L60

2022-12-13 21:15 UTC, milas commented on cmd/formatter/logs.go
> +	timestanp := time.Now().Format(jsonmessage.RFC3339NanoFixed)
Nit: `s/timestanp/timestamp/` (`n` -> `m`)

2022-12-15 14:34 UTC, milas approved these changes

2022-12-15 14:36 UTC, glours approved these changes
LGTM

2022-12-15 14:36 UTC, merged

2022-12-15 20:12 UTC, daevidvincent commented
This is exciting! I've waited literally YEARS for this. What version of `docker compose` will this show up in? 
I'm on Ubuntu and running v2.12.2 currently (from the https://docs.docker.com/compose/install/linux/ page method)

2022-12-16 07:51 UTC, ndeloof commented
Just released: https://github.com/docker/compose/releases/tag/v2.14.1

2023-01-27 06:39 UTC, od-c0d3r commented
@ndeloof, Thank you.

2024-10-15 09:51 UTC, dimikot commented
But why there is no space after the timestamp? And why it is so long, fractional digits after seconds...
```
2024-10-15T02:48:12.980702000-07:00app.service: [worker:1770481238978239
```
Should ideally be:
```
2024-10-15T02:48:12: app.service: [worker:1770481238978239
```

2024-10-15 10:05 UTC, ndeloof commented
timestamp format is set by docker engine, compose receives a pre-formatted string which is written on console