[Docs] Suggestion to add information about environment
docker/compose pull request #10095
Opened 2022-12-18 11:51 UTC by benjaoming

Signed-off-by: Benjamin Balder Bach <benjamin@overtag.dk>

**What I did**

I wondered about what happens to a container's environment when you launch commands via `exec`. Is it preserved or do I have to re-do it.

Turns out for me (Compose v2) it's nicely preserved.

Added a little general tip for debugging the environment on a running container.

2023-04-24 13:01 UTC, ndeloof approved these changes

2023-04-28 09:52 UTC, laurazard commented
I'm concerned this change will introduce more confusion than clarity.

Running `compose exec [...]` doesn't launch a new container, it executes a command in a running container, so `Environment from existing configuration is applied` isn't technically true as `compose exec` isn't applying any new environment config, that simply already exists in the running container. Maybe we can make that clear, and a new PR can be made for that, but I don't think this exact change should be made.

2023-04-28 09:53 UTC, laurazard requested changes

2023-04-28 09:53 UTC, laurazard commented on docs/reference/compose_exec.md
> +Environment from existing configuration is applied.
Maybe something like
```suggestion
Environment from existing configuration is preserved.
```
would be clearer.

2025-01-22 00:14 UTC, closed without merging

2025-01-22 11:58 UTC, benjaoming commented
haha auto-merge vs. stale bot

2025-01-22 12:07 UTC, benjaoming commented
I think by using GitHub's interface, there's something wrong with the commit data. Please feel free to use this improvement as you please.