10157 fix goroutine leak v2
docker/compose pull request #10202
Opened 2023-01-25 09:16 UTC by AhmedGrati

**What I did**
Fixed the goroutine leak, by removing the infinite goroutine that will send colors to the channel, and then refactored the `rainbowColor()` function inside the `colors.go`, to replace the logic of the infinite goroutine. 

**Related issue**

Fixes #10157.

**Screenshots of testing**
<img width="999" alt="Screen Shot 2023-01-25 at 10 07 22 AM" src="https://user-images.githubusercontent.com/48932084/214524393-ac10259a-027b-499d-9fb0-7c2dc2835e82.png">

<img width="480" alt="Screen Shot 2023-01-25 at 10 08 51 AM" src="https://user-images.githubusercontent.com/48932084/214524464-e8bf8520-6efa-4e6a-bafc-2dc5e2d7dde3.png">

2023-01-25 15:46 UTC, ndeloof requested changes

2023-01-25 15:46 UTC, ndeloof commented on cmd/formatter/colors.go
> +	result := rainbow[currentIndex]
this isn't thread safe, would require a mutex (this is why we used a channel here)

2023-01-25 16:28 UTC, ndeloof approved these changes

2023-01-25 16:51 UTC, ndeloof approved these changes

2023-01-26 09:59 UTC, glours approved these changes
LGTM

2023-01-26 11:28 UTC, laurazard approved these changes

2023-01-26 11:53 UTC, merged