Update 🥒 tests to use `dockerfile_inline`
docker/compose pull request #10508
Opened 2023-04-28 13:28 UTC by laurazard

**What I did**

Update Cucumber tests to use `dockerfile_inline` when appropriate, for clarity (and coverage).

**(not mandatory) A picture of a cute animal, if possible in relation to what you did**

![image](https://user-images.githubusercontent.com/70572044/235159885-6bbee3d0-b811-46b6-a7e3-98b78f703df7.png)

2023-04-28 13:36 UTC, ndeloof commented
LGTM. Maybe we could have both ?

2023-04-28 13:36 UTC, ndeloof approved these changes

2023-04-28 13:39 UTC, glours approved these changes

2023-04-28 13:46 UTC, laurazard commented
Yup! I changed both since the previous usecase is already thoroughly covered in the other tests, but we can add another cucumber scenario to make sure both are covered here. I'll TAL at it later.

2023-05-08 17:56 UTC, milas approved these changes

2023-05-08 17:57 UTC, milas requested changes
Oops I take-backsies my approval, there's a typo in the YAML so the CI is failing

2023-05-08 17:57 UTC, milas commented on e2e/cucumber-features/ps.feature
> +                    FROM golang:1.19-alpine
```suggestion
                dockerfile_inline: |
                    FROM golang:1.19-alpine
```

2023-05-09 10:32 UTC, laurazard commented on e2e/cucumber-features/ps.feature
> +                    FROM golang:1.19-alpine
thanks! :)

2023-05-09 16:29 UTC, milas approved these changes

2023-05-09 16:38 UTC, merged