Added option to disable log prefix via cli
docker/compose pull request #7435
Opened 2020-05-08 18:07 UTC by rohitkg98

Signed-off-by: Kaushal Rohit <rohit.kg98@gmail.com>

Resolves #7416 
Added a `--disable-log-prefix` flag to the CLI. Added additional argument to LogPresenter called `keep_prefix`.

2020-09-26 21:26 UTC, Colecf commented
Are there any updates on this PR? I would also like to use it for my system.

2020-09-27 15:51 UTC, rohitkg98 commented
Updated PR with respect to master

2020-10-03 19:14 UTC, Colecf commented
I meant more like are there any updates on getting a reviewer to look at / merge the code?

2020-10-06 13:32 UTC, rohitkg98 commented
@aiordache any updates?

2020-10-06 13:55 UTC, aiordache commented on compose/cli/log_printer.py
> +    def __init__(self, prefix_width, color_func, keep_prefix):
I would set a default for `keep_prefix` here too.

2020-10-06 13:57 UTC, aiordache approved these changes
Apart from my previous comment, SGTM! @ulyssessouza ?

2020-10-15 01:26 UTC, rohitkg98 commented
Any updates on this @ulyssessouza ?

2020-10-15 08:55 UTC, ulyssessouza requested changes
In general flags disabling something use `no` instead of `disable`.
This is the case of `--no-color`, `--no-deps`, `--no-build`, etc...

You can run `docker-compose up --help` to see some examples.

2020-10-15 08:55 UTC, ulyssessouza commented on compose/cli/log_printer.py
> +        if self.keep_prefix is True:
```suggestion
        if self.keep_prefix:
```

2020-10-17 14:39 UTC, ulyssessouza approved these changes
LGTM

2020-10-18 14:25 UTC, rohitkg98 commented
done, thanks!

2020-10-20 10:37 UTC, rohitkg98 commented
@rumpl @ndeloof any updates?

2020-11-12 08:34 UTC, merged