docker-compose pass arbitrary build flags
docker/compose pull request #7835
Opened 2020-09-28 20:49 UTC by pareshmg

added a flags option to the service.build section to pass arbitrary arguments to the docker build from the docker-compose file

Resolves #6358  (see https://github.com/docker/compose/issues/6358#issuecomment-443661538)

2020-09-28 20:51 UTC, pareshmg commented
@ciaranmcnulty : I think this implements your suggestion. 

Also, I'm new to contributing to docker-compose - I'm not quite sure how to write tests for this PR. Is there someone who can help me?

2020-10-31 13:31 UTC, djmareewish requested changes
@pareshmg #6510 #4235 
Duplicate of #

2020-10-31 17:06 UTC, pareshmg commented
> @pareshmg #6510 #4235
> Duplicate of #

@djmareewish : I don't understand how this is a duplicate of the `--squash` option. This is a more generic method to pass arbitrary flags to docker from docker-compose to help people have a route for a workaround until these parameters become official docker-compose yml syntax options. Or am I misunderstanding what you are pointing out?

2020-11-27 08:01 UTC, kiorky commented
In the meantime, i'm just using that to parse build compose args and rely on docker CLI to DRY my builds ...


```sh
# compute the docker-compose service build: args back to docker CLI build-args
buildargs=$(docker-compose config\
    |docker run -i --rm mikefarah/yq yq r - services.${service}.build.args -j\
    |docker run -i --rm imega/jq ".|to_entries[]|\" --build-arg \(.key)=\(.value)\"" -j)
# example: use squash which isnt possible now directly via compose
docker build --squash -t mytag . $buildargs
```

2022-07-27 13:57 UTC, glours commented
Thanks for taking the time to create this issue/pull request!

Unfortunately, Docker Compose V1 has reached end-of-life and we are not accepting any more changes (except for security issues). Please try and reproduce your issue with Compose V2 or rewrite your pull request to be based on the v2 branch and create a new issue or PR with the relevant Compose V2 information.

2022-07-27 13:57 UTC, closed without merging