Add `--timestamps` to up command
docker/compose pull request #8037
Opened 2021-01-17 18:06 UTC by bogdanbarna

Enable `--timestamps` for `docker up` by expanding the log_args dictionary in L1168-1171.

Resolves https://github.com/docker/compose/issues/5730

2021-01-19 17:54 UTC, aiordache requested changes
Hi! The LogPrinter needs to be updated too to print the timestamps.

2021-11-10 17:38 UTC, jkeiser commented
It looks like `docker-compose up` has been rewritten to the point that this PR will need to be completely redone. I put an [analysis](https://github.com/docker/compose/issues/5730#issuecomment-965577096) of the things that probably need to be done in the original bug. Grain of salt, I haven't looked in the Go code before today.

2021-11-24 06:58 UTC, ndeloof commented
Would better make sense indeed to reconsider this feature on the v2 branch

2021-12-20 19:14 UTC, bogdanbarna commented
Hello. I apologize for such a late reply, but somehow I got side-tracked each time I wanted to look at the feedback for this PR.
Given the rewrite from Python to Go (understandable, with all other container/cloud-native tools being built in the latter), I don't see this change being useful in any way.
Thank you for the time to look at this!

2021-12-20 19:14 UTC, closed without merging