set EnvironmentFileLabel label after ServiceHash
docker/compose pull request #8727
Opened 2021-10-01 12:20 UTC by joelbohnes

**What I did**
In order to fix #8725, we need to not include the EnvironmentFileLabel in the hash computation.
Note that the other file system path labels (WorkingDirLabel and ConfigFilesLabel) are already set after hash computation, so path changes are not an issue there. This patch brings the behaviour of EnvironmentFileLabel inline with other file system paths.

The project environment is usually set directly inside `WithServices` of `cmd/compose/compse.go`. But this needs
to be delayed until `prepareLabels` in `pkg/compose/create.go`. The easiest (but perhaps not cleanest) way
was to pass down the variable inside an extension field. Both project or service extension would work, this patch
uses a service extension field.

**Related issue**
fixes #8725

2021-10-01 13:42 UTC, ndeloof commented on cmd/compose/compose.go
> +				s.Extensions[compose.ServiceExtProjectEnvironmentFile] = ef
could be attached directly to project as this applies to all services

2021-10-01 13:45 UTC, ndeloof requested changes
I'm not a big fan using a fake extension to pass hidden parameters
could use `context.WithValue()` for this purpose

OR you can just make `ServiceHash` exclude any `com.docker.compose.*` label from hash computation are those are not tied to configuration.

2021-10-01 15:02 UTC, joelbohnes commented
I don't like the fake extension either. I think `context.WithValue` is not a clean way to pass parameters down, at least with the extension method the value is directly associated with the compose project.

Adapting `ServiceHash` seems viable, would require some custom serialization of the labels array. It seems a bit excessive, we'd only require this functionality for a single label (all other `com.docker.compose.*` labels are already set after hash computation, there is no need to adapt `SeriveHash` for them).

Another option may be to add a new field in the Project structure (in https://github.com/compose-spec/compose-go/blob/master/types/project.go). Setting the field could be done in `ProjectFromOptions` or `toProject`. I would personally prefer this option, but it requires a change in another project.

2021-10-01 15:38 UTC, ndeloof commented
> Adapting ServiceHash seems viable, would require some custom serialization of the labels array

Nope, `ServiceHash` get a copy of the ServiceConfig struct, so you can just drop all labels that start with `com.docker.compose.`

2021-10-01 16:22 UTC, joelbohnes commented
> Nope, `ServiceHash` get a copy of the ServiceConfig struct, so you can just drop all labels that start with `com.docker.compose.`

Maps are never implicitly copied (same with arrays). The ServiceConfig struct is copied, but the `Labels` member is effectively a pointer which is copied, not the whole map.

What you can do safely is to assign a the `Labels` member to a new map, like so:
```
newlabels := make(map[string]string)
for k, v := range o.Labels {
  if strings.HasPrefix(k, "com.docker.compose.") {
    newlabels[k] = v
  }
}
o.Labels = newmap
```

The comment of the `ServiceHash` function indicates that this function should eventually be moved to `compose-go`. So I don't think it's a good idea to have vendor specific label-removal functionality inside the function.

2021-10-02 15:47 UTC, ndeloof commented
> The comment of the ServiceHash function indicates that this function should eventually be moved to compose-go

I indeed added this comment as "would be nice ..." but using hash to compare actual vs requested state is very specific to docker-compose, so that's not an issue.
Also note `com.docker.compose` labels are already referenced in the spec, so don't get worried about those.

2021-11-24 08:14 UTC, ndeloof commented
I created https://github.com/docker/compose/pull/8960 as an alternative approach to this issue, I welcome your review

2023-04-24 12:51 UTC, ndeloof commented
closing as https://github.com/docker/compose/pull/8960 has been merged

2023-04-24 12:51 UTC, closed without merging