Restore missing version commands
docker/compose pull request #8738
Opened 2021-10-03 09:32 UTC by Shikachuu

**What I did**
- Removed the hidden flag from the `version` command, since by default and for historical reasons aswell it shouldn't be hidden.
- Since the documentation for the v2 still constantly reffering to a `--version` flag on the root command, I added it aswell.
_(This is up for a discuisson, since I think this change shouldn't be exist and we have to correct the documentation.)
(If we are still planning to keep this change, I think it could be done more elegantly.)_

**Related issue**
Fix #8729

**A picture of a cute animal, if possible in relation with what you did**
_(A hiding cat, reffering to the hidden version command.)_
![hidden_cat](https://i.redd.it/d2c35qq5on831.jpg)

2021-10-03 18:57 UTC, ndeloof commented
> Removed the hidden flag from the version command 

:+1, I didn't noticed we kept this one hidden, this was a mistake

> Since the documentation for the v2 still constantly reffering to a --version flag on the root command

I'm fine we introduce `--version` as this as low impact but documentation should be fixed as well.
Maybe this flag should be mark hidden so we encourage use of the explicit `version` command?

2021-10-03 19:25 UTC, Shikachuu commented
> > Removed the hidden flag from the version command
> 
> :+1, I didn't noticed we kept this one hidden, this was a mistake
> 
> > Since the documentation for the v2 still constantly reffering to a --version flag on the root command
> 
> I'm fine we introduce `--version` as this as low impact but documentation should be fixed as well. Maybe this flag should be mark hidden so we encourage use of the explicit `version` command?

I think hiding this would be a nice idea, I'll add the change soon.
Besides that, everything else looks okay?

2021-10-04 04:48 UTC, mat007 requested changes

2021-10-04 04:48 UTC, mat007 commented on cmd/compose/compose.go
> +			if version == true {
```suggestion
			if version {
```

2021-10-04 05:42 UTC, ndeloof approved these changes

2021-10-04 05:44 UTC, ndeloof commented
All good for me
Some of your commits are not signed-off. Maybe you could also squash all of them into a single one

2021-10-04 11:30 UTC, mat007 approved these changes
Thanks!

2021-10-04 16:13 UTC, Shikachuu commented
Thanks for the reviews!
Sorry I hade to do some acrobatic manovers with rebase, but now all commits squashed to one and signed-off. :laughing:

2021-10-04 16:15 UTC, merged