add more information when `service.platform` isn't part of `service.build.platforms`
docker/compose pull request #9868
Opened 2022-09-23 08:22 UTC by bkielbasa

**What I did**

I found it a bit problematic to debug so I added a bit more detailed error messages when `service.platform` isn't part of `service.build.platforms`.

2022-09-23 09:13 UTC, glours commented
@bkielbasa can you sign-off your commit? Just follow the instructions [here](https://github.com/docker/compose/pull/9868/checks?check_run_id=8510699917)

2022-09-23 09:17 UTC, glours commented on pkg/compose/build.go
> +			return nil, fmt.Errorf("service.platform %q should be part of the service.build.platforms: %q", service.Platform, service.Build.Platforms)
To be coherent, we should also update the error log line 355, can you apply the same modification?

You also need to update `TestBuildPlatformsStandardErrors` end-to-end tests in the [build_test.go ](https://github.com/docker/compose/blob/v2/pkg/e2e/build_test.go) file

2022-09-26 18:19 UTC, bkielbasa commented
@glours thanks for your review! I updated tests so it should be ready to go!

2022-09-26 18:44 UTC, glours requested changes
As your branch isn't up to date with the v2 branch, we can't merge your PR or we'll introduce potential regression. 
The only changes we should see in this PR are:
* The 2 updates of the logs
* The 2 updates in the e2e test assertions

2022-09-26 18:58 UTC, bkielbasa commented
@glours done! Sorry, I mess up with rebase :) it should be fine now

2022-09-26 19:03 UTC, glours approved these changes
LGTM, thanks for your contribution

2022-09-26 19:12 UTC, merged