fix"convert --images" output to right format
docker/compose pull request #9904
Opened 2022-10-10 02:25 UTC by Windforce17

Signed-off-by: Windforce17 <42843391+Windforce17@users.noreply.github.com>

**What I did**
According to docker images name rule: https://docs.docker.com/engine/reference/commandline/tag/#description `docker compose convert --images` should not contain underscores.

2022-10-19 12:43 UTC, milas requested changes
Thanks for the PR - good catch!

Left a comment re: the separator, as there is a global for this that gets set based on whether Compose is running in compatibility mode or not.

2022-10-19 12:43 UTC, milas commented on cmd/compose/convert.go
> +			fmt.Printf("%s-%s\n", project.Name, s.Name)
This should use `api.Separator` which will handle the compatibility case as well:
https://github.com/docker/compose/blob/32ae036fd013566cc45ceef35f5f5b7cb29725bc/pkg/api/api.go#L472-L473

2022-11-29 16:05 UTC, ndeloof commented on cmd/compose/convert.go
> +			fmt.Printf("%s\n", project.Name+api.Separator+s.Name)
as we already rely on `Printf`, better not use `+` to append strings

2022-11-30 07:05 UTC, ndeloof approved these changes

2022-11-30 14:12 UTC, glours approved these changes
LGTM

2022-12-01 08:20 UTC, merged